updated home styling
react-native-elements/playground pull request #23
Opened 2021-03-10 14:48 UTC by shivambalwani

fixed issue #3:
 changed inline styling in home page to external styling

2021-03-10 14:52 UTC, pranshuchittora commented
Thanks for the PR, but it's not recommended to use direct css due to name collisions.
Pls use the CSS module for the styling

2021-03-10 14:52 UTC, pranshuchittora commented
Ref -> https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/

2021-03-10 14:57 UTC, shivambalwani commented
> Thanks for the PR, but it's not recommended to use direct css due to name collisions.
> Pls use the CSS module for the styling

No problem sir! changing it

2021-03-10 15:25 UTC, shivambalwani commented
sir I have added css modules stylesheet in this pull request. Should i create a new branch for new pull request?

2021-03-19 21:35 UTC, pranshuchittora commented on src/pages/home/home.module.css
> +.grid{
Can you name them more specifically

2021-03-19 21:36 UTC, pranshuchittora commented on src/pages/home/home.module.css
> +.paper{
This one too

2021-03-19 21:36 UTC, pranshuchittora commented
All class names seems to generic, it would be great if they are more specific

2021-03-19 21:37 UTC, pranshuchittora requested changes
Fix class names

2021-03-21 06:24 UTC, shivambalwani commented
> Fix class names

@pranshuchittora i have fixed the style naming, but the checks are failing. I don't know why?

2021-03-26 17:55 UTC, pranshuchittora commented
Pls pull the new changes and resolve the conflicts.

2021-12-23 05:04 UTC, closed without merging