Fix some UI design and text for look more professional
react-native-elements/playground pull request #91
Opened 2021-03-21 15:30 UTC by tstariqul

Change UI design

![Screenshot from 2021-03-21 21-30-18](https://user-images.githubusercontent.com/72482679/111910703-a8624880-8a8c-11eb-9b5d-16cfa2727ab7.png)

2021-03-21 18:34 UTC, Uyadav207 requested changes
Can you resolve the conflict? @tstariqul.

-  Also kindly confirm with the maintainer, if these changes are required...?
- To resolve conflict kindly syncing the fork with upstream.

2021-03-21 18:34 UTC, Uyadav207 commented on package-lock.json
>        "requires": {
These changes are conflicting with the upstream

2021-03-22 18:32 UTC, piyushdevOP commented
[Modified] UI Text Style Changed for Professional Look #93
@flyingcircle  @pranshuchittora Please look into it .
Should I add effects to the blocks to make it more interactive ?

2021-03-23 18:37 UTC, Uyadav207 commented
@tstariqul, Please resolve the conflict in these files... and see if is the PR isn't duplicate to #93  
```
package-lock.json
src/containers/Drawer/index.jsx
src/pages/home/index.jsx
```

2021-03-26 18:19 UTC, pranshuchittora commented
Oops!
Pls pull the new changes & resolve the conflicts.

2023-03-11 03:24 UTC, closed without merging